"""DADS design token constants for the Streamlit UI.

The values are pinned to digital-go-jp/design-tokens v2.0.1:
https://github.com/digital-go-jp/design-tokens/tree/cde7dfe58d53341bba5ebae565406992fbe1218b
"""

from __future__ import annotations

DESIGN_TOKENS_VERSION = "v2.0.1"
DESIGN_TOKENS_COMMIT = "cde7dfe58d53341bba5ebae565406992fbe1218b"

COLORS: dict[str, str] = {
    "blue-50": "#e8f1fe",
    "blue-100": "#d9e6ff",
    "blue-200": "#c5d7fb",
    "blue-300": "#9db7f9",
    "blue-800": "#0031d8",
    "blue-900": "#0017c1",
    "cyan-50": "#e9f7f9",
    "cyan-100": "#c8f8ff",
    "cyan-200": "#99f2ff",
    "cyan-800": "#008299",
    "cyan-900": "#006f83",
    "green-50": "#e6f5ec",
    "green-100": "#c2e5d1",
    "green-600": "#259d63",
    "green-800": "#197a4b",
    "yellow-50": "#fbf5e0",
    "yellow-100": "#fff0b3",
    "yellow-500": "#ecc94b",
    "yellow-700": "#b78f00",
    "yellow-900": "#927200",
    "orange-50": "#ffeee2",
    "orange-100": "#ffdfca",
    "orange-600": "#fb5b01",
    "orange-800": "#c74700",
    "orange-900": "#ac3e00",
    "red-50": "#fdeeee",
    "red-100": "#ffdada",
    "red-500": "#ff5454",
    "red-800": "#ec0000",
    "red-900": "#ce0000",
    "red-1000": "#a90000",
    "red-1200": "#620000",
    "purple-50": "#f1eafa",
    "purple-100": "#ecddff",
    "purple-200": "#ddc2ff",
    "purple-800": "#5c10be",
    "magenta-50": "#f3e5f4",
    "magenta-100": "#ffd0ff",
    "magenta-800": "#aa00aa",
    "white": "#ffffff",
    "black": "#000000",
    "gray-50": "#f2f2f2",
    "gray-100": "#e6e6e6",
    "gray-200": "#cccccc",
    "gray-300": "#b3b3b3",
    "gray-400": "#999999",
    "gray-536": "#767676",
    "gray-600": "#666666",
    "gray-700": "#4d4d4d",
    "gray-800": "#333333",
    "gray-900": "#1a1a1a",
}

FONT_SANS = "'Noto Sans JP', -apple-system, BlinkMacSystemFont, sans-serif"
FONT_MONO = "'Noto Sans Mono', monospace"

RADIUS: dict[str, str] = {
    "4": "4px",
    "6": "6px",
    "8": "8px",
    "12": "12px",
    "16": "16px",
    "24": "24px",
    "32": "32px",
    "full": "9999px",
}

SPACING: dict[str, str] = {
    "0": "0",
    "1": "4px",
    "2": "8px",
    "3": "12px",
    "4": "16px",
    "5": "20px",
    "6": "24px",
    "8": "32px",
    "10": "40px",
    "12": "48px",
}

FONT_SIZE: dict[str, str] = {
    "xs": "12px",
    "sm": "14px",
    "base": "16px",
    "lg": "18px",
    "xl": "20px",
    "2xl": "24px",
    "3xl": "26px",
    "4xl": "32px",
    "score": "48px",
}

CSS_VARS: dict[str, str] = {
    "color-primary": COLORS["red-800"],
    "color-primary-hover": COLORS["red-900"],
    "color-primary-subtle": COLORS["red-50"],
    "color-primary-subtle-strong": COLORS["red-100"],
    "color-button-primary-bg": COLORS["white"],
    "color-button-primary-border": COLORS["red-800"],
    "color-button-primary-text": COLORS["red-800"],
    "color-button-primary-hover-bg": COLORS["red-800"],
    "color-button-primary-hover-border": COLORS["red-800"],
    "color-button-primary-hover-text": COLORS["white"],
    "color-button-primary-active-bg": COLORS["red-900"],
    "color-button-primary-focus-ring": COLORS["red-100"],
    "color-error": COLORS["red-900"],
    "color-error-border": COLORS["red-800"],
    "color-error-bg": COLORS["red-100"],
    "color-success": COLORS["green-800"],
    "color-success-border": COLORS["green-600"],
    "color-success-bg": COLORS["green-50"],
    "color-warning": COLORS["orange-800"],
    "color-warning-border": COLORS["orange-600"],
    "color-warning-bg": COLORS["orange-50"],
    "color-warning-yellow": COLORS["yellow-500"],
    "color-warning-yellow-bg": COLORS["yellow-50"],
    "color-info": COLORS["blue-800"],
    "color-info-border": COLORS["blue-300"],
    "color-info-bg": COLORS["blue-50"],
    "color-text": COLORS["gray-900"],
    "color-text-subtle": COLORS["gray-700"],
    "color-text-muted": COLORS["gray-600"],
    "color-disabled-text": COLORS["gray-600"],
    "color-disabled-bg": COLORS["gray-100"],
    "color-disabled-border": COLORS["gray-200"],
    "color-passed-badge-bg": COLORS["gray-100"],
    "color-surface": COLORS["white"],
    "color-surface-subtle": COLORS["gray-50"],
    "color-border": COLORS["gray-200"],
    "color-border-subtle": COLORS["gray-100"],
    "color-grid-blue-header": COLORS["blue-200"],
    "color-grid-blue-body": COLORS["blue-50"],
    "color-grid-blue-border": COLORS["blue-800"],
    "color-grid-green-header": COLORS["green-100"],
    "color-grid-green-body": COLORS["green-50"],
    "color-grid-green-border": COLORS["green-800"],
    "color-grid-cyan-header": COLORS["cyan-200"],
    "color-grid-cyan-body": COLORS["cyan-50"],
    "color-grid-cyan-border": COLORS["cyan-900"],
    "color-grid-purple-header": COLORS["purple-200"],
    "color-grid-purple-body": COLORS["purple-50"],
    "color-grid-purple-border": COLORS["purple-800"],
    "color-grid-orange-header": COLORS["orange-100"],
    "color-grid-orange-body": COLORS["orange-50"],
    "color-grid-orange-border": COLORS["orange-900"],
    "color-grid-note-bg": COLORS["gray-50"],
    "color-grid-note-border": COLORS["gray-700"],
    "color-grid-excluded": COLORS["gray-600"],
    "color-grid-excluded-bg": COLORS["gray-50"],
    "color-severity-fatal": COLORS["red-1200"],
    "color-type-text": COLORS["green-800"],
    "color-type-numeric": COLORS["blue-800"],
    "color-type-date": COLORS["orange-800"],
    "color-type-mixed": COLORS["purple-800"],
    "color-type-empty": COLORS["gray-600"],
    "font-sans": FONT_SANS,
    "font-mono": FONT_MONO,
    "radius-card": RADIUS["8"],
    "radius-control": RADIUS["8"],
    "radius-small": RADIUS["8"],
    "radius-medium": RADIUS["12"],
    "radius-large": RADIUS["16"],
    "radius-badge": RADIUS["full"],
    "space-1": SPACING["1"],
    "space-2": SPACING["2"],
    "space-3": SPACING["3"],
    "space-4": SPACING["4"],
    "space-5": SPACING["5"],
    "space-6": SPACING["6"],
    "space-8": SPACING["8"],
    "space-10": SPACING["10"],
    "font-size-xs": FONT_SIZE["xs"],
    "font-size-sm": FONT_SIZE["sm"],
    "font-size-base": FONT_SIZE["base"],
    "font-size-lg": FONT_SIZE["lg"],
    "font-size-xl": FONT_SIZE["xl"],
    "font-size-2xl": FONT_SIZE["2xl"],
    "font-size-3xl": FONT_SIZE["3xl"],
    "font-size-4xl": FONT_SIZE["4xl"],
    "font-size-score": FONT_SIZE["score"],
}

DADS_CONFIG_THEME: dict[str, str | int] = {
    "primaryColor": COLORS["red-800"],
    "backgroundColor": COLORS["white"],
    "secondaryBackgroundColor": COLORS["gray-50"],
    "textColor": COLORS["gray-900"],
    "font": FONT_SANS,
    "headingFont": FONT_SANS,
    "codeFont": FONT_MONO,
    "baseRadius": RADIUS["8"],
    "buttonRadius": RADIUS["8"],
    "baseFontSize": 16,
    "borderColor": COLORS["gray-200"],
    "dataframeBorderColor": COLORS["gray-200"],
    "dataframeHeaderBackgroundColor": COLORS["gray-50"],
}


def token_var(name: str) -> str:
    """Return a CSS variable reference for a DADS UI token."""
    return f"var(--dads-{name})"


def css_custom_properties() -> str:
    """Return the CSS custom properties block injected into Streamlit."""
    declarations = "\n".join(f"    --dads-{name}: {value};" for name, value in CSS_VARS.items())
    return f":root {{\n{declarations}\n}}\n"
